import { resolve } from 'path';
import { defineConfig } from 'vite';

export default defineConfig({
  build: {
    rollupOptions: {
      input: {
        main: resolve(__dirname, 'index.html'),
        'en-main': resolve(__dirname, 'en/index.html'),
        conditions: resolve(__dirname, 'conditions/index.html'),
        'en-conditions': resolve(__dirname, 'en/conditions/index.html'),
        confidentialite: resolve(__dirname, 'confidentialite/index.html'),
        'en-confidentialite': resolve(__dirname, 'en/confidentialite/index.html'),
        contact: resolve(__dirname, 'contact/index.html'),
        'en-contact': resolve(__dirname, 'en/contact/index.html'),
        'contact-merci': resolve(__dirname, 'contact/merci/index.html'),
        'en-contact-merci': resolve(__dirname, 'en/contact/merci/index.html'),
        blog: resolve(__dirname, 'blog/index.html'),
        'en-blog': resolve(__dirname, 'en/blog/index.html'),
        'blog-affiliation': resolve(__dirname, 'blog/affiliation/index.html'),
        'en-blog-affiliation': resolve(__dirname, 'en/blog/affiliation/index.html'),
        'blog-creer-site-affiliation': resolve(__dirname, 'blog/creer-site-affiliation/index.html'),
        'en-blog-creer-site-affiliation': resolve(__dirname, 'en/blog/creer-site-affiliation/index.html'),
        'blog-niche': resolve(__dirname, 'blog/niche/index.html'),
        'en-blog-niche': resolve(__dirname, 'en/blog/niche/index.html'),
        'blog-programmes': resolve(__dirname, 'blog/programmes/index.html'),
        'en-blog-programmes': resolve(__dirname, 'en/blog/programmes/index.html'),
        'blog-tracking': resolve(__dirname, 'blog/tracking/index.html'),
        'en-blog-tracking': resolve(__dirname, 'en/blog/tracking/index.html'),
        'blog-contenu': resolve(__dirname, 'blog/contenu/index.html'),
        'en-blog-contenu': resolve(__dirname, 'en/blog/contenu/index.html'),
        'blog-maillage': resolve(__dirname, 'blog/maillage/index.html'),
        'en-blog-maillage': resolve(__dirname, 'en/blog/maillage/index.html'),
        'blog-eeat': resolve(__dirname, 'blog/eeat/index.html'),
        'en-blog-eeat': resolve(__dirname, 'en/blog/eeat/index.html'),
        'blog-plan-30-jours': resolve(__dirname, 'blog/plan-30-jours/index.html'),
        'en-blog-plan-30-jours': resolve(__dirname, 'en/blog/plan-30-jours/index.html'),
        'blog-refresh-seo': resolve(__dirname, 'blog/refresh-seo/index.html'),
        'en-blog-refresh-seo': resolve(__dirname, 'en/blog/refresh-seo/index.html'),
        'blog-seo': resolve(__dirname, 'blog/seo/index.html'),
        'en-blog-seo': resolve(__dirname, 'en/blog/seo/index.html'),
        'mentions-legales': resolve(__dirname, 'mentions-legales/index.html'),
        'en-mentions-legales': resolve(__dirname, 'en/mentions-legales/index.html'),
        merci: resolve(__dirname, 'merci/index.html'),
        'en-merci': resolve(__dirname, 'en/merci/index.html'),
        paiement: resolve(__dirname, 'paiement/index.html'),
        'en-paiement': resolve(__dirname, 'en/paiement/index.html'),
        'paiement-annule': resolve(__dirname, 'paiement/annule/index.html'),
        'en-paiement-annule': resolve(__dirname, 'en/paiement/annule/index.html'),
        '404': resolve(__dirname, '404.html'),
      },
    },
  },
});
